# 공통 설정 (앱 이름, JPA, Flyway, Actuator 등)
spring.application.name=study-room
spring.profiles.default=local

spring.jpa.open-in-view=false
# spring.jpa.hibernate.ddl-auto=validate 설정은 JPA가 애플리케이션 시작 시 데이터베이스 스키마를 검증(Validate)만 하고, 변경하지 않는다는 의미입니다.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.jdbc.time_zone=UTC

# Flyway 데이터베이스 마이그레이션 기능 활성화
spring.flyway.enabled=true
# Flyway clean() 명령어 비활성화 (테이블과 데이터 삭제 방지)
# 언제 사용하는지? 테스트 환경에서 데이터베이스 초기화 목적으로 사용됩니다.
spring.flyway.clean-disabled=true

server.shutdown=graceful

# Actuator 기능 활성화
# health 엔드포인트는 애플리케이션의 상태를 확인하는 데 사용됩니다.
# info 엔드포인트는 애플리케이션의 정보를 확인하는 데 사용됩니다.
# show-details=never 설정은 health 엔드포인트의 상세 정보를 표시하지 않는다는 의미입니다.
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

jwt.secret=local-dev-jwt-secret-key-min-32-chars!!
jwt.access-token-settings.expiration=30m
jwt.refresh-token-settings.expiration=14d