-- btree_gist 확장 프로그램 설치
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE users (
    -- GENERATED BY DEFAULT AS IDENTITY - 값을 안넣으면 DB가 자동으로 번호를 생성.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_uq UNIQUE (email),
    CONSTRAINT users_role_ck CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT users_status_ck CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);
CREATE TABLE study_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    capacity INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT study_rooms_capacity_ck CHECK (capacity > 0),
    CONSTRAINT study_rooms_status_ck CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);
CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    room_id BIGINT NOT NULL REFERENCES study_rooms(id),
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    participant_count INTEGER NOT NULL,
    purpose VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    request_key UUID NOT NULL,
    cancelled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reservations_period_ck CHECK (start_at < end_at),
    CONSTRAINT reservations_participant_count_ck CHECK (participant_count > 0),
    CONSTRAINT reservations_status_ck CHECK (
        status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')
    ),
    -- 중복 요청으
    CONSTRAINT reservations_user_request_key_uq UNIQUE (user_id, request_key)
);
ALTER TABLE reservations -- 예약 중복 방지를 위한 EXCLUDE 제약조건 추가
ADD CONSTRAINT reservations_no_overlap EXCLUDE USING gist (
        room_id WITH =,
        tstzrange(start_at, end_at, '[)') WITH &&
    )
WHERE (status = 'CONFIRMED');
-- 아래와 같은 쿼리를 빠르게 함. - 해당 사용자 row만 좁히고 최근 예약부터 빠르게 읽을 수 있음.
-- SELECT * FROM reservations WHERE user_id = 123 ORDER BY start_at DESC;
CREATE INDEX reservations_user_start_idx ON reservations (user_id, start_at DESC);
-- 특정 공간의 예약을 시간순으로 빠르게 찾는다.
CREATE INDEX reservations_room_start_idx ON reservations (room_id, start_at);