CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO branches (name, location, time_zone)
VALUES (
        'Hong Kong',
        'Central, Hong Kong',
        'Asia/Hong_Kong'
    );
ALTER TABLE study_rooms
ADD COLUMN branch_id BIGINT REFERENCES branches(id);
UPDATE study_rooms
SET branch_id = (
        SELECT id
        FROM branches
        ORDER BY id
        LIMIT 1
    );
ALTER TABLE study_rooms
ALTER COLUMN branch_id
SET NOT NULL;
CREATE INDEX study_rooms_branch_id_idx ON study_rooms (branch_id);
ALTER TABLE study_rooms DROP COLUMN time_zone;